### ISSUE TITLE
Just wanted to say thanks for this amazing paper. 

### ISSUE THREAD

**Issue by NiluK** [princeton-computational-imaging/gensdf#4]
Hi just wanted to say this paper is amazing! I am blown away. 

This is what I did: 

- Create an image in Stable diffusion 
- Upload image to Point-E
- Upload Point-E point cloud to GEN-SDF

Image: 
![image](https://user-images.githubusercontent.com/14311730/212471917-efcc2b24-edf7-447d-9349-cb7ce7b5aea9.png)

Point-E point cloud:

https://qndkppmmrjbidgjntwgt.supabase.co/storage/v1/object/public/3d-models/items/test/55c820a2-e5d3-455a-b678-8e76e2.ply

GenSDF reconstruction:

https://qndkppmmrjbidgjntwgt.supabase.co/storage/v1/object/public/3d-models/items/336d58fe-93f8-11ed-935b-f9279e04a467/reconstruct.ply

Now, because the point-cloud is messy and noisy so is the final ply, this isn't the fault of the model and it has faithfully recreated the pointcloud

Is there a way to improve the point cloud somehow? Point-E limits it to 4k points. Do you know any models that I can input the point cloud into to get a better completed point cloud?  I am looking at using https://github.com/yuxumin/PoinTr to try it out.

Thanks!

**Comment by gene-chou** [comment]
Glad you're having fun with it :) 
I don't think a point cloud completion method such as PoinTr would work, as you are trying to refine, rather than complete, the point cloud. You might need to look into other image-to-point cloud methods. 
Another option would be a generative approach, where you use the image or the noisy point cloud as a condition to generate a new point cloud. Maybe someone has done this with diffusion.

**Comment by NiluK** [comment]
Yeah, didn't work :(. Ah well, text to 3d is insanely hard. Hopefully LION will release their paper too:

https://github.com/nv-tlabs/LION

**Comment by iamwilliamli** [comment]
> Yeah, didn't work :(. Ah well, text to 3d is insanely hard. Hopefully LION will release their paper too:
> 
> https://github.com/nv-tlabs/LION

Have you tried using LION to reconstruct this?
