### ISSUE TITLE
Question about the dataset

### ISSUE THREAD

**Issue by pigtigger** [princeton-computational-imaging/gensdf#5]
Thanks for your great work!
I am confused about the data processing. I first download the ShapentSem meshes ( 12490 obj files), and then download the 1.6GB acronym h5 data, which contains 8836 h5 files. After parsing the 8836 h5 files to get the corresponding mesh names in ShapnetSem by `grasps['object/file'][()]`, I find there are some h5 files refer to the same obj files and I only get 7897 matched meshes. I am wondering how to get the 8872 objects according to your paper, it would be great if you can provide me more details about the dataprocessing.

Btw, GenSDF uses the watertight meshes, I am wondering if the watertight meshes could improve the performance, can I just use your scripts to process original ShapeNet data to obtain SDF training data?

**Comment by gene-chou** [comment]
To be honest it's been too long since I downloaded the acronym dataset, but the ShapeNet dataset should work. Meshes must be watertight by definition of SDFs. You can use my preprocessing code and discard all meshes that are not watertight. This is also a great repo https://github.com/marian42/mesh_to_sdf for preprocessing.
